version: 2
formats: [htmlzip, pdf]
python:
   version: 3.6
   install:
      - method: pip
        path: .
        extra_requirements:
          - gevent
          - mongodb
          - redis
          - rethinkdb
          - sqlalchemy
          - tornado
          - twisted
          - zookeeper
          - doc
