version: "2"
services:
  postgresql:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: secret

  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379

  mongodb:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_REPLICA_SET_NAME: foo

  rethinkdb:
    image: rethinkdb
    ports:
      - 127.0.0.1:28015:28015

  zookeeper:
    image: zookeeper
    ports:
      - 127.0.0.1:2181:2181
